import {
  treatmentProfileIds,
  assessmentProfileIds,
  outcomeProfileIds,
  patientProfileIds,
  diseaseProfileIds,
  genomicsProfileIds,
} from './coverageProfileIds';

const fieldIds = {
  [patientProfileIds.cancerPatientId]: [
    'Name',
    'Contact Info',
    'Birth Date',
    'Gender',
    'Zip Code',
    'US Core Race',
    'US Core Ethnicity',
    'Deceased',
  ],
  [diseaseProfileIds.tumorMarkerTestId]: ['Result Value', 'Test Type'],
  [diseaseProfileIds.primaryCancerConditionId]: [
    'Asserted Date',
    'Histology/Morphology',
    'Body Site',
    'Laterality',
    'Location Qualifier',
  ],
  [diseaseProfileIds.secondaryCancerConditionId]: ['Related Condition'],
  [diseaseProfileIds.stageGroupId]: ['Staging System', 'Clinical/Pathological'],
  [diseaseProfileIds.primaryTumorId]: ['Result Value'],
  [diseaseProfileIds.distantMetastasesId]: ['Result Value'],
  [diseaseProfileIds.regionalNodesId]: ['Result Value'],
  [outcomeProfileIds.diseaseStatusId]: ['Evidence Type'],
  [outcomeProfileIds.tumorId]: ['Body Structure Identifier', 'Location'],
  [outcomeProfileIds.tumorSizeId]: ['Method', 'Component', 'Longest Dimension', 'Other Dimension'],
  [outcomeProfileIds.tumorSpecimenId]: ['Type'],
  [assessmentProfileIds.comorbiditiesId]: [
    'Risk Score',
    'Component',
    'Present/Absent',
    'Condition Code',
    'Condition Reference',
  ],
  [assessmentProfileIds.ecogPerformanceStatusId]: ['Score', 'Interpretation'],
  [assessmentProfileIds.karnofskyPerformanceStatusId]: ['Score', 'Interpretation'],
  [treatmentProfileIds.cancerRelatedMedicationAdministrationId]: [
    'Medication',
    'Reason',
    'Procedure Intent',
    'Termination Reason',
  ],
  [treatmentProfileIds.cancerRelatedMedicationRequestId]: [
    'Medication',
    'Reason',
    'Procedure Intent',
    'Termination Reason',
  ],
  [treatmentProfileIds.cancerRelatedSurgicalProcedureId]: [
    'Procedure Code',
    'Body Site',
    'Laterality',
    'Location Qualifier',
  ],
  [treatmentProfileIds.radiotherapyCourseSummaryId]: [
    'No. Sessions',
    'Modality and Technique',
    'Modality',
    'Technique',
    'Doses Delivered',
    'Total Dose',
    'No. Fractions',
    'Body Volume',
  ],
  [treatmentProfileIds.radiotherapyVolumeId]: ['Volume Type', 'Location', 'Location Qualifier'],
  [genomicsProfileIds.genomicRegionStudiedId]: [
    'Component',
    'Gene Mutations',
    'Gene Studied',
    'Coordinate System',
    'DNA Ranges Examined',
    'DNA Region Description',
    'Reference Sequence ID',
  ],
  [genomicsProfileIds.genomicSpecimenId]: ['Collection Site', 'Specimen Type'],
  [genomicsProfileIds.genomicVariantId]: [
    'Present/Absent',
    'Component',
    'Variation',
    'DNA Change',
    'DNA Change Type',
    'Amino Acid Change',
    'Amino Acid Change Type',
    'Molecular Consequence',
    'Clinical Significance',
    'Gene Studied',
    'Genomic Source Class',
    'Copy Number',
    'Allelic Frequency',
    'Allelic State',
    'Cytogenic Location',
    'Cytogen. Nomenclature',
  ],
  [genomicsProfileIds.genomicsReportId]: ['Test Type', 'Result'],
};

export default fieldIds;
